apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.128.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus/self:
        config:
          scrape_configs:
            - job_name: otel-collector-self
              static_configs:
                - targets:
                    - localhost:8888
    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: 0.0.0.0:8889
      prometheusremotewrite:
        endpoint: http://prometheus-kube-prometheus-prometheus.monitoring:9090/api/v1/write
    processors:
      batch: {}
    extensions:
      pprof:
        endpoint: 0.0.0.0:1777
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        metrics:
          exporters:
            - debug
            - prometheus
            - prometheusremotewrite
          processors:
            - batch
          receivers:
            - otlpl
            - prometheus/self
          extensions: 
           - pprof
  ports:
    - name: metrics
      port: 8889
      protocol: TCP
    - name: pprof
      port: 1777
      targetPort: 1777
      protocol: TCP
