apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.128.0
  config: |
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch: {}
    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:8889"
      prometheus/self:
        config:
          scrape_configs:
          - job_name: otel-collector-self
            static_configs:
            - targets: ["localhost:8888"]
      prometheusremotewrite:
        endpoint: "http://prometheus-kube-prometheus-prometheus.monitoring:9090/api/v1/write"
    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus/self]
          processors: [batch]
          exporters: [debug, prometheus, prometheusremotewrite]
  ports:
    - name: metrics
      port: 8889
      protocol: TCP
