apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.128.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus/self:
        config:
          scrape_configs:
            - job_name: otel-collector-self
              static_configs:
                - targets:
                    - localhost:8888
    exporters:
      datadog:
        api:
          key: 98f8b6cf3a5d492f450edba4b6a41d18
          site: datadoghq.com
        host_metadata:
          enabled: false
        metrics:
          resource_attributes_as_tags: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_elapsed_time: 10m
          max_interval: 30s
        sending_queue:
          enabled: true
          num_consumers: 20000
          queue_size: 200000
        timeout: 30s
        tls:
          insecure_skip_verify: true
      debug:
        verbosity: detailed
      prometheus:
        endpoint: 0.0.0.0:8889
      prometheusremotewrite:
        endpoint: http://prometheus-kube-prometheus-prometheus.monitoring:9090/api/v1/write
    processors:
      batch: {}
    extensions:
      pprof:
        endpoint: 0.0.0.0:1777
    service:
      telemetry:
        metrics:
          level: normal
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
      pipelines:
        metrics:
          exporters:
            - debug
            - prometheus
            - prometheusremotewrite
          processors:
            - batch
          receivers:
            - otlpl
            - prometheus/self
  ports:
    - name: metrics
      port: 8889
      protocol: TCP
    - name: pprof
      port: 1777
      targetPort: 1777
      protocol: TCP
